package org.huokan.client.models.wow;

public enum WeaponType {
    POLEARM, ONE_HANDED_AXE, ONE_HANDED_SWORD, ONE_HANDED_MACE, TWO_HANDED_AXE, TWO_HANDED_SWORD, TWO_HANDED_MACE,
    WARGLAIVE, FIST_WEAPON, HELD_IN_OFF_HAND, DAGGER, STAFF, WAND, SHIELD, BOW, CROSSBOW, GUN;
}
